spring.datasource.url=jdbc:mysql://localhost:3306/ticketdb
spring.datasource.username=root
spring.datasource.password=929093

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081